[package]
name = "poker"
version = "3.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good-web-game = "0.4.1"
miniquad = "=0.3.0-alpha.37"
cgmath = { version = "0.17", features = ["mint"] }
quad-rand = "0.2.1"